

import Head from "next/head"
export default function Header() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          rel="stylesheet"
        />

        <link
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          rel="stylesheet"
        />

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.1.0/mdb.min.css"
          rel="stylesheet"
        />
      </Head>

      <nav className=" navbar fixed-top navbar-expand-lg navbar-dark pink scrolling-navbar bg-white  px-3 container ">
        <a className="navbar-brand" href="#">
          <img src="https://th.bing.com/th/id/OIP.AkUK82FTvYQ-oXMsOXP0AAHaHa?pid=ImgDet&rs=1" width="50" height="50" />"
        </a>
        <div className="collapse navbar-collapse flex justify-content-between" id="navbarSupportedContent">

          <ul className="navbar-nav mr-auto  align-items-center">
            <li className="nav-item active py-3 ">
              <a className="nav-link text-black " href="#">Home <span className="sr-only">(current)</span></a>
            </li>
            <li className="nav-item py-3 ps-5">
              <a className="nav-link text-black " href="#">About</a>
            </li>
            <li className="nav-item py-3 px-5">
              <a className="nav-link text-black " href="#">Contact</a>
            </li>
            <li className="nav-item ">
              <a className="nav-link text-white  py-3 px-5 btn btn-success rounded-9" href="#">Follow</a>
            </li>
          </ul>
          <ul className="navbar-nav  align-items-center">
            <li className="nav-item ">
              <a className="nav-link text-black px-5">Sing In</a>
            </li>
            <li className="nav-item">
              <a className="nav-link text-success  py-3 px-4 btn btn-outline-success rounded-9" >Get Started</a>
            </li>
          </ul>
        </div>
      </nav>
    </>


  )
}
